env: dev
debug: true
logPath: "/Users/nova/works/go-gin-layout/test/"

server:
  port: 8011

database:
  dsn: root:qq123456@tcp(127.0.0.1:3306)/wallet_test?charset=utf8mb4&parseTime=True&loc=Local
  debug: true

redis:
  addr: localhost:6379
  password: ""
  db: 0
  debug: true

jwt:
  secret: mysecret
  expire: 3600

lark:
  webhookURL: "https://open.feishu.cn/open-apis/bot/v2/hook/your-webhook-url"
