server:
  port: 8011

database:
  dsn: root:qq123456@tcp(127.0.0.1:3306)/wallet_test?charset=utf8mb4&parseTime=True&loc=Local

redis:
  addr: localhost:6379
  password: ""
  db: 0

jwt:
  secret: mysecret
  expire: 3600
